[package]
name = "qna-warp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
warp = { version = "0.3.7", features = ["default"]}
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"